databases:
  - name: gen3-kotonohaDB
    databaseName: gen3_kotonoha_db
    user: harukimedes
    region: singapore

services:
  - type: web
    name: Gen3-kotonoha
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV.fetch('DATABASE_URL') %>
        fromDatabase:
          name: gen3-kotonohaDB
          property: connectionString
      - key: <%= ENV.fetch('RAILS_MASTER_KEY') %>
        sync: false
