databases:
  - name: gen3-kotonohaDB
    databaseName: gen3_kotonoha_db
    user: harukimedes
    region: singapore

services:
  - type: web
    name: gen3-kotonohaDB
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: Renderで作成したDBアプリ名
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
